# Generated by Django 6.0.2 on 2026-02-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="description",
            field=models.TextField(verbose_name="Описание разершения"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя разрешения"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название роли"),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.permission",
                verbose_name="ИД разрешения",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.role",
                verbose_name="ИД роли",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.role",
                verbose_name="ИД Роли",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="ИД пользователя",
            ),
        ),
    ]
