# Generated by Django 6.0.2 on 2026-02-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="name",
        ),
        migrations.AddField(
            model_name="permission",
            name="create_permission",
            field=models.BooleanField(default=False, verbose_name="create permission"),
        ),
        migrations.AddField(
            model_name="permission",
            name="delete_all_permission",
            field=models.BooleanField(
                default=False, verbose_name="delete all permission"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="delete_permission",
            field=models.BooleanField(default=False, verbose_name="delete permission"),
        ),
        migrations.AddField(
            model_name="permission",
            name="read_all_permission",
            field=models.BooleanField(
                default=False, verbose_name="read all permission"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="read_permission",
            field=models.BooleanField(default=False, verbose_name="read"),
        ),
        migrations.AddField(
            model_name="permission",
            name="update_all_permission",
            field=models.BooleanField(
                default=False, verbose_name="update all permission"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="update_permission",
            field=models.BooleanField(default=False, verbose_name="update permission"),
        ),
    ]
