# Generated by Django 6.0.2 on 2026-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_permission_description_remove_permission_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="create_permission",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="delete_all_permission",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="delete_permission",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="read_all_permission",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="read_permission",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="update_all_permission",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="update_permission",
        ),
        migrations.AddField(
            model_name="permission",
            name="can_create",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на создание"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="can_delete",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на удаление"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="can_delete_all",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на удаление любых записей"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="can_read",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на чтение"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="can_read_all",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на чтение всего"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="can_update",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на обновление"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="can_update_all",
            field=models.BooleanField(
                default=False, verbose_name="Разрешение на обновление всего"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="description",
            field=models.TextField(default="", verbose_name="Описание разрешения"),
        ),
        migrations.AddField(
            model_name="permission",
            name="name",
            field=models.CharField(
                default="Нет имени", max_length=100, verbose_name="Имя разрешения"
            ),
        ),
    ]
