# Generated by Django 6.0.2 on 2026-02-12 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_permission_create_permission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Роль", "verbose_name_plural": "Роли"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="exp_at",
            field=models.DateTimeField(null=True, verbose_name="Время истечения"),
        ),
        migrations.AddField(
            model_name="user",
            name="session_tk",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Токен сессии"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания токена"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название роли"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="пароль"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="users.role",
                verbose_name="ИД Роли",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ИД пользователя",
            ),
        ),
        migrations.AlterModelTable(
            name="role",
            table="roles",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.CreateModel(
            name="Permission_role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_read",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на чтение"
                    ),
                ),
                (
                    "can_read_all",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на чтение всех"
                    ),
                ),
                (
                    "can_create",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на создание"
                    ),
                ),
                (
                    "can_update",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на обновление"
                    ),
                ),
                (
                    "can_update_all",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на обновление всех"
                    ),
                ),
                (
                    "can_delete",
                    models.BooleanField(
                        default=False, verbose_name="Разрешение на удаление"
                    ),
                ),
                (
                    "can_delete_all",
                    models.BooleanField(
                        default=False,
                        verbose_name="Разрешение на удаление любых записей",
                    ),
                ),
                (
                    "business_element",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Permission_role",
                        to="users.businesselement",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Permission_role",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Права доступа",
                "db_table": "Permission",
                "unique_together": {("role", "business_element")},
            },
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
