# Generated by Django 6.0.2 on 2026-02-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_businesselement_remove_rolepermission_permission_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="permission_role",
            table="Permission_role",
        ),
        migrations.AlterModelTable(
            name="userrole",
            table="UserRole",
        ),
    ]
