# Generated by Django 6.0.2 on 2026-02-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_permission_role_table_alter_userrole_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="permission_role",
            table="permission_role",
        ),
        migrations.AlterModelTable(
            name="userrole",
            table="user_role",
        ),
    ]
