# Generated by Django 6.0.2 on 2026-02-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_permission_role_table_alter_userrole_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="permission_role",
            unique_together={("role",)},
        ),
        migrations.RemoveField(
            model_name="permission_role",
            name="business_element",
        ),
        migrations.DeleteModel(
            name="BusinessElement",
        ),
    ]
