# Generated by Django 6.0.2 on 2026-02-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_permission_role_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_roles",
                to="users.role",
                verbose_name="ИД Роли",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ИД пользователя",
            ),
        ),
    ]
